"""add org stripe fields

Revision ID: 782db7a1760f
Revises: ab0d1a9c5b68
Create Date: 2026-07-15 16:22:09.291621+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "782db7a1760f"
down_revision: str | None = "ab0d1a9c5b68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("stripe_customer_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "organizations", sa.Column("stripe_subscription_id", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_organizations_stripe_subscription_id"),
        "organizations",
        ["stripe_subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organizations_stripe_subscription_id"), table_name="organizations")
    op.drop_column("organizations", "stripe_subscription_id")
    op.drop_column("organizations", "stripe_customer_id")
    # ### end Alembic commands ###
