"""add optimization and metrics tables

Revision ID: dab4b6fec409
Revises: c5eb86af5a74
Create Date: 2026-07-14 12:09:17.173328+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dab4b6fec409"
down_revision: str | None = "c5eb86af5a74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_metrics",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column("campaign_id", sa.String(length=40), nullable=False),
        sa.Column("ad_group_id", sa.String(length=40), nullable=False),
        sa.Column("ad_id", sa.String(length=40), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("ctr", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("conversions", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ad_metrics_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_metrics")),
        sa.UniqueConstraint(
            "organization_id", "customer_id", "ad_id", "date", name="uq_ad_metric_day"
        ),
    )
    op.create_index(op.f("ix_ad_metrics_customer_id"), "ad_metrics", ["customer_id"], unique=False)
    op.create_index(op.f("ix_ad_metrics_date"), "ad_metrics", ["date"], unique=False)
    op.create_index(
        op.f("ix_ad_metrics_organization_id"), "ad_metrics", ["organization_id"], unique=False
    )
    op.create_table(
        "campaign_metrics",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column("campaign_id", sa.String(length=40), nullable=False),
        sa.Column("campaign_name", sa.String(length=255), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("conversions", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("conversions_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("ctr", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("average_cpc", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cpa", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("roas", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_campaign_metrics_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_metrics")),
        sa.UniqueConstraint(
            "organization_id", "customer_id", "campaign_id", "date", name="uq_campaign_metric_day"
        ),
    )
    op.create_index(
        op.f("ix_campaign_metrics_campaign_id"), "campaign_metrics", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_metrics_customer_id"), "campaign_metrics", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_campaign_metrics_date"), "campaign_metrics", ["date"], unique=False)
    op.create_index(
        op.f("ix_campaign_metrics_organization_id"),
        "campaign_metrics",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "daily_performance_reports",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("totals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_daily_performance_reports_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_performance_reports")),
        sa.UniqueConstraint("organization_id", "customer_id", "date", name="uq_daily_report"),
    )
    op.create_index(
        op.f("ix_daily_performance_reports_customer_id"),
        "daily_performance_reports",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_performance_reports_date"),
        "daily_performance_reports",
        ["date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_performance_reports_organization_id"),
        "daily_performance_reports",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "keyword_metrics",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column("campaign_id", sa.String(length=40), nullable=False),
        sa.Column("ad_group_id", sa.String(length=40), nullable=False),
        sa.Column("criterion_id", sa.String(length=40), nullable=False),
        sa.Column("keyword_text", sa.String(length=255), nullable=True),
        sa.Column("match_type", sa.String(length=20), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("conversions", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cost_per_conversion", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_keyword_metrics_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keyword_metrics")),
        sa.UniqueConstraint(
            "organization_id",
            "customer_id",
            "ad_group_id",
            "criterion_id",
            "date",
            name="uq_keyword_metric_day",
        ),
    )
    op.create_index(
        op.f("ix_keyword_metrics_campaign_id"), "keyword_metrics", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_keyword_metrics_customer_id"), "keyword_metrics", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_keyword_metrics_date"), "keyword_metrics", ["date"], unique=False)
    op.create_index(
        op.f("ix_keyword_metrics_organization_id"),
        "keyword_metrics",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notifications_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False)
    op.create_index(
        op.f("ix_notifications_organization_id"), "notifications", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_type"), "notifications", ["type"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "optimization_policies",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_execute", sa.Boolean(), nullable=False),
        sa.Column("max_budget_increase_pct", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_budget_decrease_pct", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_bid_change_pct", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("min_days_active", sa.Integer(), nullable=False),
        sa.Column("min_clicks_required", sa.Integer(), nullable=False),
        sa.Column("min_keyword_clicks", sa.Integer(), nullable=False),
        sa.Column("min_keyword_days", sa.Integer(), nullable=False),
        sa.Column("min_confidence", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("date_range", sa.String(length=40), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_optimization_policies_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimization_policies")),
        sa.UniqueConstraint(
            "organization_id", name=op.f("uq_optimization_policies_organization_id")
        ),
    )
    op.create_table(
        "optimization_logs",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("customer_id", sa.String(length=20), nullable=True),
        sa.Column("campaign_id", sa.String(length=40), nullable=True),
        sa.Column("action_type", sa.String(length=48), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=True),
        sa.Column("previous_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("new_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("api_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_optimization_logs_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_optimization_logs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_optimization_logs_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimization_logs")),
    )
    op.create_index(
        op.f("ix_optimization_logs_action_type"), "optimization_logs", ["action_type"], unique=False
    )
    op.create_index(
        op.f("ix_optimization_logs_campaign_id"), "optimization_logs", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_optimization_logs_customer_id"), "optimization_logs", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_optimization_logs_organization_id"),
        "optimization_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_optimization_logs_status"), "optimization_logs", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_optimization_logs_status"), table_name="optimization_logs")
    op.drop_index(op.f("ix_optimization_logs_organization_id"), table_name="optimization_logs")
    op.drop_index(op.f("ix_optimization_logs_customer_id"), table_name="optimization_logs")
    op.drop_index(op.f("ix_optimization_logs_campaign_id"), table_name="optimization_logs")
    op.drop_index(op.f("ix_optimization_logs_action_type"), table_name="optimization_logs")
    op.drop_table("optimization_logs")
    op.drop_table("optimization_policies")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_organization_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_keyword_metrics_organization_id"), table_name="keyword_metrics")
    op.drop_index(op.f("ix_keyword_metrics_date"), table_name="keyword_metrics")
    op.drop_index(op.f("ix_keyword_metrics_customer_id"), table_name="keyword_metrics")
    op.drop_index(op.f("ix_keyword_metrics_campaign_id"), table_name="keyword_metrics")
    op.drop_table("keyword_metrics")
    op.drop_index(
        op.f("ix_daily_performance_reports_organization_id"), table_name="daily_performance_reports"
    )
    op.drop_index(op.f("ix_daily_performance_reports_date"), table_name="daily_performance_reports")
    op.drop_index(
        op.f("ix_daily_performance_reports_customer_id"), table_name="daily_performance_reports"
    )
    op.drop_table("daily_performance_reports")
    op.drop_index(op.f("ix_campaign_metrics_organization_id"), table_name="campaign_metrics")
    op.drop_index(op.f("ix_campaign_metrics_date"), table_name="campaign_metrics")
    op.drop_index(op.f("ix_campaign_metrics_customer_id"), table_name="campaign_metrics")
    op.drop_index(op.f("ix_campaign_metrics_campaign_id"), table_name="campaign_metrics")
    op.drop_table("campaign_metrics")
    op.drop_index(op.f("ix_ad_metrics_organization_id"), table_name="ad_metrics")
    op.drop_index(op.f("ix_ad_metrics_date"), table_name="ad_metrics")
    op.drop_index(op.f("ix_ad_metrics_customer_id"), table_name="ad_metrics")
    op.drop_table("ad_metrics")
    # ### end Alembic commands ###
