"""add campaign creation tables

Revision ID: c5eb86af5a74
Revises: c60c62970372
Create Date: 2026-07-13 23:47:08.101955+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c5eb86af5a74"
down_revision: str | None = "c60c62970372"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_profiles",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("business_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("industry", sa.String(length=160), nullable=False),
        sa.Column("website_url", sa.String(length=1024), nullable=True),
        sa.Column("product_service_description", sa.Text(), nullable=True),
        sa.Column("usp", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("target_countries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_cities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("languages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("goal", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_business_profiles_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_business_profiles_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_profiles")),
    )
    op.create_index(
        op.f("ix_business_profiles_deleted_at"), "business_profiles", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_business_profiles_organization_id"),
        "business_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "audience_profiles",
        sa.Column("business_profile_id", sa.UUID(), nullable=False),
        sa.Column("age_min", sa.Integer(), nullable=True),
        sa.Column("age_max", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("locations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("interests", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pain_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("existing_customer_profile", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_profile_id"],
            ["business_profiles.id"],
            name=op.f("fk_audience_profiles_business_profile_id_business_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audience_profiles")),
        sa.UniqueConstraint(
            "business_profile_id", name=op.f("uq_audience_profiles_business_profile_id")
        ),
    )
    op.create_table(
        "budget_configurations",
        sa.Column("business_profile_id", sa.UUID(), nullable=False),
        sa.Column("daily_budget", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("monthly_budget", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("max_cpa", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("target_roas", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_profile_id"],
            ["business_profiles.id"],
            name=op.f("fk_budget_configurations_business_profile_id_business_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_configurations")),
        sa.UniqueConstraint(
            "business_profile_id", name=op.f("uq_budget_configurations_business_profile_id")
        ),
    )
    op.create_table(
        "campaign_blueprints",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("business_profile_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("customer_id", sa.String(length=20), nullable=True),
        sa.Column("campaign_name", sa.String(length=255), nullable=False),
        sa.Column("campaign_type", sa.String(length=40), nullable=False),
        sa.Column("objective", sa.String(length=120), nullable=False),
        sa.Column("daily_budget", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("bidding_strategy", sa.String(length=60), nullable=False),
        sa.Column("structure", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("google_campaign_id", sa.String(length=40), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_profile_id"],
            ["business_profiles.id"],
            name=op.f("fk_campaign_blueprints_business_profile_id_business_profiles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_campaign_blueprints_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_campaign_blueprints_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_campaign_blueprints_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_blueprints")),
    )
    op.create_index(
        op.f("ix_campaign_blueprints_customer_id"),
        "campaign_blueprints",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_blueprints_deleted_at"),
        "campaign_blueprints",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_blueprints_organization_id"),
        "campaign_blueprints",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_blueprints_status"), "campaign_blueprints", ["status"], unique=False
    )
    op.create_table(
        "product_information",
        sa.Column("business_profile_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("pricing", sa.String(length=120), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("benefits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("landing_url", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_profile_id"],
            ["business_profiles.id"],
            name=op.f("fk_product_information_business_profile_id_business_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_information")),
    )
    op.create_index(
        op.f("ix_product_information_business_profile_id"),
        "product_information",
        ["business_profile_id"],
        unique=False,
    )
    op.create_table(
        "website_analyses",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("business_profile_id", sa.UUID(), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("business_summary", sa.Text(), nullable=False),
        sa.Column("products", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("services", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_customer", sa.Text(), nullable=False),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selling_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommended_strategy", sa.Text(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_profile_id"],
            ["business_profiles.id"],
            name=op.f("fk_website_analyses_business_profile_id_business_profiles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_website_analyses_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_website_analyses")),
    )
    op.create_index(
        op.f("ix_website_analyses_business_profile_id"),
        "website_analyses",
        ["business_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_website_analyses_organization_id"),
        "website_analyses",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "campaign_execution_logs",
        sa.Column("blueprint_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("google_resource_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blueprint_id"],
            ["campaign_blueprints.id"],
            name=op.f("fk_campaign_execution_logs_blueprint_id_campaign_blueprints"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_campaign_execution_logs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_execution_logs")),
    )
    op.create_index(
        op.f("ix_campaign_execution_logs_blueprint_id"),
        "campaign_execution_logs",
        ["blueprint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_execution_logs_organization_id"),
        "campaign_execution_logs",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_campaign_execution_logs_organization_id"), table_name="campaign_execution_logs"
    )
    op.drop_index(
        op.f("ix_campaign_execution_logs_blueprint_id"), table_name="campaign_execution_logs"
    )
    op.drop_table("campaign_execution_logs")
    op.drop_index(op.f("ix_website_analyses_organization_id"), table_name="website_analyses")
    op.drop_index(op.f("ix_website_analyses_business_profile_id"), table_name="website_analyses")
    op.drop_table("website_analyses")
    op.drop_index(
        op.f("ix_product_information_business_profile_id"), table_name="product_information"
    )
    op.drop_table("product_information")
    op.drop_index(op.f("ix_campaign_blueprints_status"), table_name="campaign_blueprints")
    op.drop_index(op.f("ix_campaign_blueprints_organization_id"), table_name="campaign_blueprints")
    op.drop_index(op.f("ix_campaign_blueprints_deleted_at"), table_name="campaign_blueprints")
    op.drop_index(op.f("ix_campaign_blueprints_customer_id"), table_name="campaign_blueprints")
    op.drop_table("campaign_blueprints")
    op.drop_table("budget_configurations")
    op.drop_table("audience_profiles")
    op.drop_index(op.f("ix_business_profiles_organization_id"), table_name="business_profiles")
    op.drop_index(op.f("ix_business_profiles_deleted_at"), table_name="business_profiles")
    op.drop_table("business_profiles")
    # ### end Alembic commands ###
