"""add usage records

Revision ID: ab0d1a9c5b68
Revises: f71797b61bc4
Create Date: 2026-07-14 14:33:38.832471+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab0d1a9c5b68"
down_revision: str | None = "f71797b61bc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_records",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("feature", sa.String(length=48), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_usage_records_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
        sa.UniqueConstraint(
            "organization_id", "feature", "period", name="uq_usage_org_feature_period"
        ),
    )
    op.create_index(op.f("ix_usage_records_feature"), "usage_records", ["feature"], unique=False)
    op.create_index(
        op.f("ix_usage_records_organization_id"), "usage_records", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_usage_records_period"), "usage_records", ["period"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_records_period"), table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_organization_id"), table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_feature"), table_name="usage_records")
    op.drop_table("usage_records")
    # ### end Alembic commands ###
