"""add google ads tables

Revision ID: 0c06a5f65c76
Revises: fe54537fafc9
Create Date: 2026-07-13 23:14:57.162361+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c06a5f65c76"
down_revision: str | None = "fe54537fafc9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "google_ads_connections",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("authorized_by_user_id", sa.UUID(), nullable=True),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=False),
        sa.Column("scopes", sa.String(length=512), nullable=False),
        sa.Column("login_customer_id", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["authorized_by_user_id"],
            ["users.id"],
            name=op.f("fk_google_ads_connections_authorized_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_google_ads_connections_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_google_ads_connections")),
    )
    op.create_index(
        op.f("ix_google_ads_connections_organization_id"),
        "google_ads_connections",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_ads_connections_status"), "google_ads_connections", ["status"], unique=False
    )
    op.create_table(
        "google_ads_accounts",
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column("descriptive_name", sa.String(length=255), nullable=True),
        sa.Column("currency_code", sa.String(length=8), nullable=True),
        sa.Column("time_zone", sa.String(length=64), nullable=True),
        sa.Column("is_manager", sa.Boolean(), nullable=False),
        sa.Column("is_test_account", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["google_ads_connections.id"],
            name=op.f("fk_google_ads_accounts_connection_id_google_ads_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_google_ads_accounts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_google_ads_accounts")),
        sa.UniqueConstraint("organization_id", "customer_id", name="uq_ads_account_org_customer"),
    )
    op.create_index(
        op.f("ix_google_ads_accounts_connection_id"),
        "google_ads_accounts",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_ads_accounts_customer_id"),
        "google_ads_accounts",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_ads_accounts_organization_id"),
        "google_ads_accounts",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_google_ads_accounts_organization_id"), table_name="google_ads_accounts")
    op.drop_index(op.f("ix_google_ads_accounts_customer_id"), table_name="google_ads_accounts")
    op.drop_index(op.f("ix_google_ads_accounts_connection_id"), table_name="google_ads_accounts")
    op.drop_table("google_ads_accounts")
    op.drop_index(op.f("ix_google_ads_connections_status"), table_name="google_ads_connections")
    op.drop_index(
        op.f("ix_google_ads_connections_organization_id"), table_name="google_ads_connections"
    )
    op.drop_table("google_ads_connections")
    # ### end Alembic commands ###
