"""add ai insights and memory importance

Revision ID: 6782ebff3259
Revises: dab4b6fec409
Create Date: 2026-07-14 13:59:38.836864+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6782ebff3259"
down_revision: str | None = "dab4b6fec409"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_insights",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("insight_type", sa.String(length=48), nullable=False),
        sa.Column("observation", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("importance_score", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_insights_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_insights")),
    )
    op.create_index(
        op.f("ix_ai_insights_insight_type"), "ai_insights", ["insight_type"], unique=False
    )
    op.create_index(
        op.f("ix_ai_insights_organization_id"), "ai_insights", ["organization_id"], unique=False
    )
    op.add_column(
        "agent_memories",
        sa.Column("importance_score", sa.Numeric(precision=4, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_memories", "importance_score")
    op.drop_index(op.f("ix_ai_insights_organization_id"), table_name="ai_insights")
    op.drop_index(op.f("ix_ai_insights_insight_type"), table_name="ai_insights")
    op.drop_table("ai_insights")
    # ### end Alembic commands ###
